S3:
  IP: '12.57.247.123'
  PORT: 1621
  SERVICE_NAME:
  USER:
  PASSWORD:

17:
  IP:
  PORT:
  SERVICE_NAME:
  USER:
  PASSWORD:

LOCAL:
  IP: '127.0.0.1'
  PORT: 1521
  SERVICE_NAME:
  USER:
  PASSWORD: